PZWeb/urls.py
from obras import views
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('inicio.urls')),  
    path('admin/', admin.site.urls),
    path('obras/', include('obras.urls')),
    path('bio/', include('bio.urls')),
    path('produccion/', include('produccion.urls')),
    path('contacto/', include('contacto.urls')),
    #path('obras/', views.obras, name = "Obras"),   ESTO SI FUNCIONA SIN EL INCLUDE
]

#Esta linea para que se muestren ok las imagenes.
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bio/urls.py
from django.urls import path
from . import views

app_name = 'bio'

urlpatterns = [
    path('', views.bio, name = "Bio"),   
]

contacto/urls.py
from django.urls import path
from . import views

app_name = 'contacto'

urlpatterns = [
    path('', views.contacto, name = "Contacto"),    
]

inicio/urls.py
from django.urls import path
from . import views

app_name = 'inicio'

urlpatterns = [
    path('', views.inicio, name = "Inicio"),   

]

obras/urls.py
from django.urls import path
from . import views

app_name = 'obras'

urlpatterns = [
    path('', views.obras, name = "Obras"),   
    path('obras_alta/', views.obras_alta, name = "ObrasAlta"),   
    path('obras_detalle/<int:obra_id>', views.obra_detalle, name = "ObraDetalle"),  
]

produccion/urls.py
from django.urls import path
from . import views

app_name = 'produccion'

urlpatterns = [
    path('', views.produccion, name = "Produccion"),   
    path('produccion_detalle/<int:proyecto_id>', views.produccion_detalle, name = "ProduccionDetalle"),  
]

bio/models.py
from django.db import models

# Create your models here.

contacto/models.py
from django.db import models

# Create your models here.

inicio/models.py
from django.db import models

# Create your models here.

obras/models.py
from tkinter import CASCADE
from django.db import models
from pymysql import NULL

# Create your models here.

class CategoriaObra(models.Model):
    nombre = models.CharField(max_length=50)
    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now_add=True)

    class Meta():
        verbose_name = "Categoria Obra"
        verbose_name_plural = "Categorias Obra"  

    def __str__(self):
        return self.nombre


class Obra (models.Model):
    titulo = models.CharField(max_length=50)
    disciplina = models.ForeignKey(CategoriaObra, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='obras', null=True, blank=True)
    imagen2 = models.ImageField(upload_to='obras', null=True, blank=True)
    imagen3 = models.ImageField(upload_to='obras', null=True, blank=True)
    imagen4 = models.ImageField(upload_to='obras', null=True, blank=True)
    imagen5 = models.ImageField(upload_to='obras', null=True, blank=True)
    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now_add=True)
    descripcion = models.TextField(default='')
    bajada = models.CharField(max_length=100, default='')
    lugar = models.CharField(max_length=100, default='Ushuaia')
    anio = models.PositiveIntegerField(default=2014)

    class Meta():
        #orden por defecto a menos que se sobreescriba otro orden
        ordering = ['-anio']

    def __str__(self):
        return self.titulo

produccion/models.py
from distutils.command.upload import upload
from django.db import models
from pymysql import NULL

# Create your models here.

class Produccion(models.Model):

    titulo = models.CharField(max_length=100)
    bajada = models.CharField(max_length=300)
    descripcion = models.TextField(default='')
    lugar = models.CharField(max_length=100)
    imagen = models.ImageField(upload_to='produccion', blank=True, null=True)
    imagen2 = models.ImageField(upload_to='produccion', blank=True, null=True)
    imagen3 = models.ImageField(upload_to='produccion', blank=True, null=True)
    imagen4 = models.ImageField(upload_to='produccion', blank=True, null=True)
    imagen5 = models.ImageField(upload_to='produccion', blank=True, null=True)
    anio = models.PositiveIntegerField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    class Meta():
        #orden por defecto a menos que se sobreescriba otro orden
        ordering = ['-anio']
        verbose_name = "Producción"
        verbose_name_plural = "Producciones"

    def __str__(self):
        return self.titulo

contacto/forms.py
from django import forms

class Contacto (forms.Form):
    nombre = forms.CharField(label='Tu nombre', max_length=100)
    mensaje = forms.CharField(widget=forms.Textarea(attrs={'name':'mensaje', 'rows':4, 'cols':30}))
    email = forms.EmailField(label='Email')

obras/forms.py
from turtle import width
from django import forms
from pkg_resources import require
from .models import CategoriaObra

categorias = CategoriaObra.objects.all()
OPCIONES = []
for c in categorias:
    OPCIONES.append(
        (c.id, c.nombre)
    )

class FormularioCategoria(forms.Form):
    categoria= forms.CharField(widget=forms.Select(choices=OPCIONES))

bio/views.py
from django.shortcuts import render

# Create your views here.

def bio (request):
    return render (request, "bio/bio.html")

contacto/views.py
from django.shortcuts import redirect, render
from .forms import Contacto
from django.core.mail import send_mail

# Create your views here.

def contacto (request):

    if request.method == "POST":
        form = Contacto(request.POST)
        if form.is_valid():
            nombre = form.cleaned_data['nombre']
            mensaje = form.cleaned_data['mensaje']
            sender = form.cleaned_data['email']
            recipients = ['paulazuc@gmail.com']
            subject = 'Mensaje desde la web'
            message = nombre + ' te ha enviado un mensaje. Su correo es: ' + sender + ' y su mensaje: ' + mensaje
            
            try:
                send_mail(subject, message, sender, recipients)
                return redirect('/contacto/?sent')
            except:
                return redirect('/contacto/?error')
            
    else:
        form = Contacto()

    return render(request, "contacto/contacto.html", {'form' : form})

inicio/views.py
from django.shortcuts import render
from obras.models import Obra


# Create your views here.

def inicio (request):
    obras = Obra.objects.all().order_by('-anio')[:3]
    return render (request, "inicio/index.html", {'obras':obras})   

obras/views.py
from tkinter import CASCADE
from django.http import HttpResponse
from django.shortcuts import redirect, render
from obras import models
from .models import Obra, CategoriaObra
from .forms import FormularioCategoria
from django.forms import ModelForm
from django.db import models

# Create your views here.

# Create the form class. 
class ObraForm(ModelForm):   
    titulo = models.CharField(max_length=50)
    disciplina = models.ForeignKey(CategoriaObra, on_delete=models.CASCADE)
    #imagen = models.ImageField(upload_to='obras', null=True, blank=True)

    class Meta:
        model = Obra
        fields = ['titulo', 'disciplina', 'imagen']
          

def obras (request):
    if request.method == "POST":
        form = FormularioCategoria(request.POST)
        if form.is_valid():
            cat=form.cleaned_data["categoria"]
            obras = Obra.objects.filter(disciplina_id=cat)
    else:
        form = FormularioCategoria()
        obras = Obra.objects.all()
    categorias = CategoriaObra.objects.all()
    return render (request, "obras/obras.html", {'obras':obras, 'categorias':categorias, 'form':form})

def obras_alta (request):
    if request.method == "POST":
        form = ObraForm(request.POST)
        if form.is_valid():
            form.save()
            return render (request, "obras/obras_alta.html")
    else:
        form = ObraForm()
    return render (request, "obras/obras_alta.html", {'form':form})


def obra_detalle(request, obra_id):
    obra = Obra.objects.get(id=obra_id)
    return render (request, "obras/obra_detalle.html", {'obra':obra})

produccion/views.py
from django.shortcuts import render

from produccion.models import Produccion

# Create your views here.


def produccion(request):
    proyectos = Produccion.objects.all()

    return render(request, 'produccion/produccion.html', {'proyectos':proyectos})

def produccion_detalle(request, proyecto_id):
    proyecto = Produccion.objects.get(id=proyecto_id)
    return render(request, 'produccion/produccion_detalle.html', {'proyecto':proyecto})

bio/templates/bio/bio.html
{% extends "inicio/base.html" %}

{% load static %}

{% block content %}


    <!-- ======= Works Section ======= -->
    <section class="section site-portfolio">
      <div class="container">
        <div class="row mb-5 align-items-center">
          <div class="col-md-12 col-lg-6 mb-4 mb-lg-0" data-aos="fade-up">
            <h2>Bio</h2>
            <p class="mb-0"></p>
          </div>

          {% include "inicio/menu.html" %}

        </div>

        <!-- fin header -->

        <div id="portfolio-grid" class="row no-gutter" data-aos="fade-up" data-aos-delay="200">
            <p>Soy coreógrafa, bailarina y productora en el campo de las artes escénicas. <br />
            Licenciada en Composición Coreográfica por la Universidad Nacional de las Artes, en el año 2015 
            cursé el Posgrado en Gestión Cultural de la Universidad Nacional de Córdoba. 
            En 2016-2017 fui becada por el Ministerio de Cultura de la Nación para participar del 
            Programa de Formación en Gestión Cultural Pública (Río Negro - Buenos Aires).
            <br /><br />
            Desde el año 2014 formo parte del equipo de Casa de las Artes, Secretaría de Extensión de la 
            Universidad Nacional de Tierra del Fuego, A. e I. A. S., 
            en el área de Producción Artística desarrollando, entre otras, actividades en el campo de las 
            artes escénicas: espacios de formación, encuentros con y entre artistas, presentaciones de obras, etc. 
            <br /><br />
            En 2021 dirigí TURBA - Festival Nacional de Artes Escénicas de Ushuaia, con el apoyo del 
            Instituto Nacional del Teatro, organismos locales y un grupo hermoso de personas que con trabajo y amor lo hicieron posible. En 2022, TURBA participó como Festival
            demandante en el MICA - Mercado de Industrias Culturales de Argentina, y del programa Argentina Florece Danza, presentando una obra de su programación en Tecnópolis (Bs As).
            <br /><br />
            Desde el año 2015 y hasta hoy, trabajo en la generación de espacios de formación en Ushuaia y Río Grande, en el ámbito de la danza y el teatro,
            con apoyo del Fondo Nacional de las Artes, el Instituto Nacional del Teatro, la Municipalidad de Ushuaia, entre otros. Algunxs de lxs
            artistas y docentes involucradxs en estas experiencias fueron Luis Biasotto, Carlos Osatinsky, Fernando Pellicioli,
            Lautaro Vilo, Victoria Keriluk, Gastón Exequiel Sánchez, Yamila Guillermo, Yamina Leiva, Macarena Higueras, entre otrxs. 
            <br /><br />
                     
            Como creadora, participo desde 2020 de un grupo de investigación en danza, junto con Yamina Leiva y Macarena Higueras.
            Estrené "Paralaje - una conferencia escénica" (Ushuaia) y "Nos faltará siempre yo" (Bs As), con 
            apoyo del Fondo Argentino de Desarrollo Cultural y Creativo y del Instituto Nacional del Teatro. 
            <br /><br />
            Como docente, desde el año 2012 dicto clases de danza clásica, danza contemporánea e investigación del movimiento, orientadas a niñxs y adultxs, 
            en la Universidad Nacional de Tierra del Fuego, en Chic! Academia, y en espacios independientes de la ciudad.</p>
              <p></p><br /><br /><br /><br /><br />
        </div>
      </div>
    </section><!-- End  Works Section -->
    {% endblock %}

contacto/templates/contacto/contacto.html
{% extends "inicio/base.html" %}

{% load static %}

{% block content %}


    <!-- ======= Works Section ======= -->
    <section class="section site-portfolio">
      <div class="container">
        <div class="row mb-5 align-items-center">
          <div class="col-md-12 col-lg-6 mb-4 mb-lg-0" data-aos="fade-up">
            <h2>Contacto</h2>
            <p class="mb-0"></p>
          </div>

          {% include "inicio/menu.html" %}

        </div>

        <!-- fin header -->
        {{ mensaje }}

        
        <div id="portfolio-grid" class="row no-gutter" data-aos="fade-up" data-aos-delay="200">

          {% if "sent" in request.GET %}
            <p>Gracias!</p>
          {% else %}
            <form action="" method="post">
              {% csrf_token %}
              <table>
              {{ form.as_table }}
              </table>
              <input type="submit" value="Submit">
            </form>
          {% endif %}
        </div>
      </div>
    </section><!-- End  Works Section -->
    {% endblock %}

inicio/templates/inicio/base.html
<!DOCTYPE html>
<html lang="en">

<head>

  {% load static %}

  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Bailar las preguntas</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="assets/img/favicon.png" rel="icon">
  <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Bootstrap -->
  <link href="{% static 'inicio/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'inicio/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'inicio/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'inicio/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
   

  <!-- Styles -->
  <link href="{% static 'inicio/css/style.css' %}" rel="stylesheet">
  
  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=https://fonts.googleapis.com/css?family=Inconsolata:400,500,600,700|Raleway:400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

</head>

<body>
<!--
  <div class="collapse navbar-collapse custom-navmenu" id="main-navbar">
    <div class="container py-2 py-md-5">
      <div class="row align-items-start">
        <div class="col-md-2">
          <ul class="custom-menu">
            <li class="active"><a href="{% url 'inicio:Inicio' %}">Inicio</a></li>
            <li><a href="{% url 'bio:Bio' %}">Acerca de mí</a></li>
            <li><a href="works.html">Proyectos</a></li>
            <li><a href="contact.html">Contacto</a></li>
          </ul>
        </div>
        <div class="col-md-6 d-none d-md-block  mr-auto">
          <div class="tweet d-flex">
            <span class="bi bi-twitter text-white mt-2 mr-3"></span>
            <div>
              <p><em>Acá hay fotos, textos, videos y otros materiales sobre algunos proyectos que realicé. <br> </em></p>
            </div>
          </div>
        </div>

      </div>

    </div>
  </div>
-->
  <nav class="navbar navbar-light custom-navbar">
    <div class="container">
      <a class="navbar-brand" href="{% url 'inicio:Inicio' %}">BAILAR LAS PREGUNTAS</a>
      <!--<a href="#" class="burger" data-bs-toggle="collapse" data-bs-target="#main-navbar">-->
        <span></span>
      </a>
    </div>
  </nav>

  <main id="main">

        
   <!-- Contenido cambiante -->

  {% block content %} {% endblock %}


        <!-- footer -->

    </main><!-- End #main -->

 
         <!-- ======= Footer ======= -->
  <footer class="footer" role="contentinfo">
    <div class="container">
      <div class="row">
        <div class="col-sm-6">
          <div class="credits">
          
        </div>

      </div>
    </div>
  </footer>

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy" crossorigin="anonymous"></script>

  <script src="{% static 'inicio/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'inicio/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <script src="{% static 'inicio/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'inicio/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'inicio/vendor/php-email-form/validate.js' %}"></script>
  <script src="{% static 'inicio/js/main.js' %}"></script>
</body>

</html>

inicio/templates/inicio/index.html
{% extends "inicio/base.html" %}

{% load static %}

{% block content %}


    <!-- ======= Works Section ======= -->
    <section class="section site-portfolio">
      <div class="container">
        <div class="row mb-5 align-items-center">
          <div class="col-md-12 col-lg-6 mb-4 mb-lg-0" data-aos="fade-up">
            <!--<h2></h2>-->
            <p class="mb-0">¡Hola! Soy Paula Zucchello, bailarina y productora artística. En esta plataforma hay fotos, textos, videos y otros materiales sobre algunos proyectos en los que participo o participé.</p>
          </div>
        {% include "inicio/menu.html" %}
        </div>
        <!-- fin header -->

        <div id="portfolio-grid" class="row no-gutter" data-aos="fade-up" data-aos-delay="200">

          {% for obra in obras %}

          <div class="item obras col-sm-6 col-md-4 col-lg-4 mb-4">
            <a href="{% url 'obras:ObraDetalle' obra.id %}" class="item-wrap fancybox">
              <div class="work-info">
                <h3>{{obra.titulo}}</h3>
                <span>{{obra.disciplina}}</span>
              </div>
              <img class="img-fluid" src="{{obra.imagen.url}}">
            </a>
          </div>
          
          {% endfor %}

      
        </div>
      </div>
    </section><!-- End  Works Section -->
    {% endblock %}

inicio/templates/inicio/menu.html
    <div class="col-md-12 col-lg-6 text-start text-lg-end" data-aos="fade-up" data-aos-delay="100">
      <div class="filters">
        <a href="{% url 'obras:Obras' %}" {% if request.path|slice:":5" == "/obra" %} class="active" {% endif %}>Creación</a>
        <a href="{% url 'produccion:Produccion' %}">Producción</a>
        <a href="{% url 'bio:Bio' %}" {% if request.path == "/bio/" %} class="active" {% endif %}>Bio</a>
        <a href="{% url 'contacto:Contacto' %}">Contacto</a>
      </div>
    </div>

obras/templates/obras/obra_detalle.html
{% extends "inicio/base.html" %}

{% load static %}

{% block content %}


    <!-- ======= Works Section ======= -->
    <section class="section site-portfolio">
      <div class="container">
        <div class="row mb-5 align-items-center">
          <div class="col-md-12 col-lg-6 mb-4 mb-lg-0" data-aos="fade-up">
            <h2>{{obra.titulo}}</h2>
            <p class="mb-0">{{obra.disciplina}}</p>
          </div>

            {% include "inicio/menu.html" %}

        </div>

        <!-- fin header -->

      <div class="site-section pb-0">
        <div class="container">
          <div class="row align-items-stretch">
            <div class="col-md-8" data-aos="fade-up">
              <img src="{{obra.imagen.url}}" alt="Image" class="img-fluid">
            </div>
            <div class="col-md-3 ml-auto" data-aos="fade-up" data-aos-delay="100">
              <div class="sticky-content">
                <h3 class="h3">{{obra.titulo}}</h3>
                <p class="mb-4"><span class="text-muted">{{obra.bajada}}</span></p>

                <div class="mb-5">
                  <p>{{obra.descripcion}}</p>

                </div>

                <ul class="list-unstyled list-line mb-5">
                  <li>Año: {{obra.anio}}</li>
                  <li>Lugar: {{obra.lugar}}</li>
                </ul>

              </div>
            </div>
          </div>
        </div>
    </section>

    <!-- ======= Testimonials Section ======= -->
    <section class="section pt-0">
      <div class="container">

        <div class="testimonials-slider swiper" data-aos="fade-up" data-aos-delay="100">
          <div class="swiper-wrapper">

            <div class="swiper-slide">
              <div class="testimonial-wrap">
                <div class="testimonial">
                  <img src="assets/img/person_1.jpg" alt="Image" class="img-fluid">
                  <blockquote>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam necessitatibus incidunt ut officiis
                      explicabo inventore.</p>
                  </blockquote>
                  <p>&mdash; Jean Hicks</p>
                </div>
              </div>
            </div><!-- End testimonial item -->

            <div class="swiper-slide">
              <div class="testimonial-wrap">
                <div class="testimonial">
                  <img src="assets/img/person_2.jpg" alt="Image" class="img-fluid">
                  <blockquote>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam necessitatibus incidunt ut officiis
                      explicabo inventore.</p>
                  </blockquote>
                  <p>&mdash; Chris Stanworth</p>
                </div>
              </div>
            </div><!-- End testimonial item -->

          </div>
          <div class="swiper-pagination"></div>
        </div>

      </div>
    </section><!-- End Testimonials Section -->

    {% endblock %}

obras/templates/obras/obras.html
{% extends "inicio/base.html" %}

{% load static %}

{% block content %}


    <!-- ======= Works Section ======= -->
    <section class="section site-portfolio">
      <div class="container">
        <div class="row mb-5 align-items-center">
          <div class="col-md-12 col-lg-6 mb-4 mb-lg-0" data-aos="fade-up">
            <!--<h2></h2>-->
            <p class="mb-0">Proyectos / Obras</p>
          </div>
        {% include "inicio/menu.html" %}
        </div>
        <!-- fin header -->

        <div id="portfolio-grid" class="row no-gutter" data-aos="fade-up" data-aos-delay="200">

          {% for obra in obras %}

          <div class="item obras col-sm-6 col-md-4 col-lg-4 mb-4">
            <a href="{% url 'obras:ObraDetalle' obra.id %}" class="item-wrap fancybox">
              <div class="work-info">
                <h3>{{obra.titulo}}</h3>
                <span>{{obra.disciplina}}</span>
              </div>
              <img class="img-fluid" src="{{obra.imagen.url}}">
            </a>
          </div>
          
          {% endfor %}

      
        </div>
      </div>
    </section><!-- End  Works Section -->
    {% endblock %}

obras/templates/obras/obras_alta.html
<html>
    <tile>Mis obras</tile>
    <body>

        <p><ul>
            {% for m in error_messages %}
                <li>{{ m }}</li>
            {% endfor %} 
            </ul>
        </p>
        <form action="" method="post">
            {% csrf_token %} 
            {{form.as_p}}
            <input type="submit" value="Enviar">
        </form>

    </body>
</html>

produccion/templates/produccion/produccion.html
{% extends "inicio/base.html" %}

{% load static %}

{% block content %}


    <!-- ======= Works Section ======= -->
    <section class="section site-portfolio">
      <div class="container">
        <div class="row mb-5 align-items-center">
          <div class="col-md-12 col-lg-6 mb-4 mb-lg-0" data-aos="fade-up">
            <!--<h2></h2>-->
            <p class="mb-0">Producción / Gestión</p>
          </div>
        {% include "inicio/menu.html" %}
        </div>
        <!-- fin header -->

        <div id="portfolio-grid" class="row no-gutter" data-aos="fade-up" data-aos-delay="200">

          {% for proyecto in proyectos %}

          <div class="item obras col-sm-6 col-md-4 col-lg-4 mb-4">
            <a href="{% url 'produccion:ProduccionDetalle' proyecto.id %}" class="item-wrap fancybox">
              <div class="work-info">
                <h3>{{proyecto.titulo}}</h3>
                <span>{{proyecto.disciplina}}</span>
              </div>
              <img class="img-fluid" src="{{proyecto.imagen.url}}">
            </a>
          </div>
          
          {% endfor %}

      
        </div>
      </div>
    </section><!-- End  Works Section -->
    {% endblock %}

produccion/templates/produccion/produccion_detalle.html
{% extends "inicio/base.html" %}

{% load static %}

{% block content %}


    <!-- ======= Works Section ======= -->
    <section class="section site-portfolio">
      <div class="container">
        <div class="row mb-5 align-items-center">
          <div class="col-md-12 col-lg-6 mb-4 mb-lg-0" data-aos="fade-up">
            <h2>{{obra.titulo}}</h2>
            <p class="mb-0">{{obra.disciplina}}</p>
          </div>

            {% include "inicio/menu.html" %}

        </div>

        <!-- fin header -->

      <div class="site-section pb-0">
        <div class="container">
          <div class="row align-items-stretch">
            <div class="col-md-8" data-aos="fade-up">
              <img src="{{proyecto.imagen.url}}" alt="Image" class="img-fluid">
            </div>
            <div class="col-md-3 ml-auto" data-aos="fade-up" data-aos-delay="100">
              <div class="sticky-content">
                <h3 class="h3">{{proyecto.titulo}}</h3>
                <p class="mb-4"><span class="text-muted">{{proyecto.bajada}}</span></p>

                <div class="mb-5">
                  <p>{{proyecto.descripcion}}</p>

                </div>

                <ul class="list-unstyled list-line mb-5">
                  <li>Año: {{proyecto.anio}}</li>
                  <li>Lugar: {{proyecto.lugar}}</li>
                </ul>

              </div>
            </div>
          </div>
        </div>
    </section>

    
    {% endblock %}